name: CI/CD for dbt Project

on:
  pull_request:
    branches:
      - main  # Run tests when a PR targets master
  push:
    branches:
      - dev  # Run tests on dev branch pushes  
      - main  # Deploy to production when pushing to maste

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv dbt-env
          source dbt-env/bin/activate
          pip install dbt-core dbt-snowflake

      - name: Set up Snowflake private key
        run: |
            echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}" | base64 --decode > /tmp/snowflake_key.p8
            chmod 600 /tmp/snowflake_key.p8


      - name: Set up dbt profiles
        run: |
          mkdir -p ~/.dbt
          echo "my_fraud_detection_project:" > ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      database: DEV_FRAUD_DETECTION" >> ~/.dbt/profiles.yml
          echo "      authenticator: snowflake_jwt" >> ~/.dbt/profiles.yml
          echo "      private_key_path: /tmp/snowflake_key.p8" >> ~/.dbt/profiles.yml
          echo "      role: ACCOUNTADMIN" >> ~/.dbt/profiles.yml
          echo "      schema: PUBLIC" >> ~/.dbt/profiles.yml
          echo "      threads: 2" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
          echo "      warehouse: MY_DBT_WAREHOUSE" >> ~/.dbt/profiles.yml
          echo "    prod:" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      database: PROD_FRAUD_DETECTION" >> ~/.dbt/profiles.yml
          echo "      authenticator: snowflake_jwt" >> ~/.dbt/profiles.yml
          echo "      private_key_path: /tmp/snowflake_key.p8" >> ~/.dbt/profiles.yml
          echo "      role: ACCOUNTADMIN" >> ~/.dbt/profiles.yml
          echo "      schema: PUBLIC" >> ~/.dbt/profiles.yml
          echo "      threads: 2" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
          echo "      warehouse: MY_DBT_WAREHOUSE" >> ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml

      - name: Run dbt deps
        run: |
          source dbt-env/bin/activate
          dbt deps

      - name: Run dbt test
        run: |
          source dbt-env/bin/activate
          dbt test --target dev  # Run tests on the dev environment

  deploy:
    needs: test  # Only run if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv dbt-env
          source dbt-env/bin/activate
          pip install dbt-core dbt-snowflake

      - name: Set up Snowflake private key
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}" | base64 --decode > /tmp/snowflake_key.p8
          chmod 600 /tmp/snowflake_key.p8

      - name: Set up dbt profiles for prod
        run: |
          mkdir -p ~/.dbt
          echo "my_fraud_detection_project:" > ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      database: DEV_EMEKA_FRAUD_DETECTION" >> ~/.dbt/profiles.yml
          echo "      authenticator: snowflake_jwt" >> ~/.dbt/profiles.yml
          echo "      private_key_path: /tmp/snowflake_key.p8" >> ~/.dbt/profiles.yml
          echo "      role: ACCOUNTADMIN" >> ~/.dbt/profiles.yml
          echo "      schema: PUBLIC" >> ~/.dbt/profiles.yml
          echo "      threads: 2" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
          echo "      warehouse: MY_DBT_WAREHOUSE" >> ~/.dbt/profiles.yml
          echo "    prod:" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      database: PROD_FRAUD_DETECTION2" >> ~/.dbt/profiles.yml
          echo "      authenticator: snowflake_jwt" >> ~/.dbt/profiles.yml
          echo "      private_key_path: /tmp/snowflake_key.p8" >> ~/.dbt/profiles.yml
          echo "      role: ACCOUNTADMIN" >> ~/.dbt/profiles.yml
          echo "      schema: PUBLIC" >> ~/.dbt/profiles.yml
          echo "      threads: 2" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
          echo "      warehouse: MY_DBT_WAREHOUSE" >> ~/.dbt/profiles.yml
          echo "  target: prod" >> ~/.dbt/profiles.yml

      - name: Run dbt models for production
        run: |
          source dbt-env/bin/activate
          dbt run --target prod  # Run models in production after tests pass